# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - prestinec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code #Chat edit from: []
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies #Chat edit from: Build with dotnet
        run: dotnet restore Prestine_Solution/Prestine_Solution.sln

      - name: Build the solution #Chat edit from: dotnet publish 
        run: dotnet build Prestine_Solution/Prestine_Solution.sln --configuration Release

      - name: Publish the application #Chat edit from: dotnet publish 
        run: dotnet publish Prestine_Solution/Api/Api.csproj -c Release -o "${{ runner.temp }}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ runner.temp }}/myapp #Chat edit from: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B877ABCE371F4A48B10D6C13F2AABEC5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40A3CDBCF41E422BB6B5FE3C3C3DFAFE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C7FC23484CCC43FB9D810FAC5444AD34 }}

      - name: Set up Google and Firebase Secrets
        run: |
            echo "Google__ClientId=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
            echo "Google__ClientSecret=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prestinecare'
          slot-name: 'Production'
          package: .
          